---
name: "Build and tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci-version:
    uses: jgsogo/composite/.github/workflows/_parse_version.yml@master
    with:
      github_sha: ${{ github.sha }}

  ci:
    uses: jgsogo/composite/.github/workflows/_build.yml@master
    with:
      library_name: composite
      github_sha: ${{ github.sha }}
