---
name: "Build and tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    uses: jgsogo/composite/.github/workflows/_build.yml@master
    with:
      library_name: composite
      github_sha: ${{ github.sha }}
    secrets:
      RT_USERNAME: ${{ secrets.RT_USERNAME }}
      RT_TOKEN: ${{ secrets.RT_TOKEN }}
