---
name: "Build and tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    uses: jgsogo/composite/.github/workflows/_build.yml@master
    with:
      library_name: composite
      github_sha: ${{ github.sha }}
    secrets:
      remote_username: ${{ secrets.RT_USERNAME }}
      remote_token: ${{ secrets.RT_TOKEN }}
