---
# TODO: This job probably belongs to jgsogo/conan-recipes
name: Conan Package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CONAN_USER_HOME: /home/conan

defaults:
  run:
    working-directory: /home/conan

jobs:
  test_conan_package:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu16.04:1.44.0
    env:
      CONAN_USER_HOME: /home/conan
    steps:
      - name: Upgrade Git version
        working-directory: /home/conan
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common -y
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update
          sudo apt-get install git -y

      - name: Check out repository code
        uses: rodrigorodriguescosta/checkout@main  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          path: /home/conan/library

      - name: Check out recipes repository
        uses: rodrigorodriguescosta/checkout@main  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          repository: jgsogo/conan-recipes
          path: /home/conan/conan-recipes

      - name: Add version to conandata.yml
        run: |
            echo "  \"${{ github.sha }}\":" >> conan-recipes/recipes/${{ github.event.repository.name }}/all/conandata.yml
            echo "    url: https://github.com/${{ github.repository }}/archive/${{ github.sha }}.zip" >> conan-recipes/recipes/${{ github.event.repository.name }}/all/conandata.yml
            cat conan-recipes/recipes/${{ github.event.repository.name }}/all/conandata.yml

      - name: Run create
        run: |
          for profile in library/.conan/profiles/* ; do
            conan create conan-recipes/recipes/${{ github.event.repository.name }}/all/conanfile.py ${{ github.event.repository.name }}/${{ github.sha }}@jgsogo/testing --profile:host=$profile --profile:build=default
          done
