---
# TODO: This job probably belongs to jgsogo/conan-recipes
name: Conan Package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_recipe:
    uses: jgsogo/conan-recipes/.github/workflows/_test_recipe.yml@master
    with:
      github_sha: ${{ github.sha }}
      github_ref_name: ${{ github.event.repository.name }}
      repository: ${{ github.repository }}
