---
name: "(Manual) Create new release"

on: workflow_dispatch

jobs:
  ci:
    uses: jgsogo/composite/.github/workflows/_build.yml@master
    with:
      library_name: composite
      github_sha: master

  ci-version:
    uses: jgsogo/composite/.github/workflows/_parse_version.yml@master
    with:
      github_sha: master

  release-available:
    needs:
      ci-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --tags
          git tag | tail -1
          LATEST_TAG=$(git tag | tail -1)
          echo ${LATEST_TAG}

  create_release:
    needs:
      - ci
      - release-available
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          automatic_release_tag: "v${{ needs.ci-version.outputs.LIBRARY_VERSION }}"

