---
name: "Published Release"

on:
  release:
    types: [published]

jobs:
  new_release:
    uses: jgsogo/conan-recipes/.github/workflows/_published_release.yml@master
    with:
      github_sha: ${{ github.sha }}
      github_ref_name: ${{ github.ref_name }}
      github_repository: ${{ github.repository }}
    secrets:
      APP_RECIPES_APP_ID: ${{ secrets.APP_RECIPES_APP_ID }}
      APP_RECIPES_PRIVATE_KEY: ${{ secrets.APP_RECIPES_PRIVATE_KEY }}
