---
# TODO: This job probably belongs to jgsogo/conan-recipes
name: "Published Release"

on:
  release:
    types: [published]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: "Print information"
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.sha: ${{ github.sha }}"

      - name: "Open PR to jgsogo/conan-recipes"
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.sha: ${{ github.sha }}"

