name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Check the tag
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        run: |
          echo $SOURCE_TAG

  ci:
    needs: test_tag
    uses: jgsogo/composite/.github/workflows/_build.yml@master
    with:
      library_name: composite
      github_sha: ${{ github.sha }}

  create_release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
